name: PlotSquared
main: com.intellectualcrafters.plot.PlotMain
version: 2.1.2
load: STARTUP
description: >
             Easy, yet powerful Plot World generation and management.
authors: [Citymonstret, Empire92]
softdepend: [WorldEdit, BarAPI, PlotMe, CameraAPI]
database: false
commands:
  plots:
    description: PlotMain PlotSquared command.
    aliases: [p,plotme,plot,ps,plotsquared,p2]
    permission: plots.use
    permission-message: "You are lacking the permission node 'plots.use'"
permissions:
  plots.use:
    default: op
  plots.admin:
    default: op
  plots.worldedit.bypass:
    default: false